### ISSUE TITLE
Importing team does not work

### ISSUE THREAD

**Issue by eboumendil** [terraform-providers/terraform-provider-tfe#23]
Importing team does not work and I am getting an invalid team import format error, see below:

```
 eboumendil@C02VD27BHV2H # terraform import tfe_team.test TeWWKkK1yDNrHgoz        
                                                   
tfe_team.test: Importing from ID "TeWWKkK1yDNrHgoz"...

Error: tfe_team.test (import id: TeWWKkK1yDNrHgoz): import tfe_team.test (id: TeWWKkK1yDNrHgoz): invalid team import format: TeWWKkK1yDNrHgoz
```

**Comment by svanharmelen** [comment]
Hi @eboumendil! Looking at the ID you are trying to use, it looks like you missed part of the ID.

A team ID always starts with `team-`, so if you omitted that part you could try it again including that part. If your ID does not start with `team-` you are probably looking at the wrong ID.

Let me know if this solves your problem or if you need help finding the correct ID.

**Comment by svanharmelen** [comment]
May I ask how you determined the team ID? And are you using the TFE SaaS solution or PTFE?

**Comment by svanharmelen** [comment]
No, that should work as expected. Hmm. I think I see what the problem is:

`Error: tfe_team.bsi (import id: team-TeWWKkK1yDNrHgoz): import tfe_team.test (id: team-TeWWKkK1yDNrHgoz): invalid team import format: team-TeWWKkK1yDNrHgoz`

So the internal ID (name) of the team in your TF config is `bsi`? If that is correct then the correct command is: 

`import tfe_team.bsi (id: team-TeWWKkK1yDNrHgoz`

But I must admit the error is a bit vague on this one (if this is indeed the problem).

**Comment by eboumendil** [comment]
I tried to  change the name for github but  I did run `terraform import tfe_team.bsi team-TeWWKkK1yDNrHgoz`

**Comment by svanharmelen** [comment]
Hmm... I've looked at the code and I think the docs may be wrong for the import statement. Could you try this command:

`terraform import tfe_team.bsi  org_name/team_name`

If this works, I update the docs to properly reflect this!

**Comment by eboumendil** [comment]
Magic! It works!

**Comment by svanharmelen** [comment]
Nice! I’ll update the docs 👍🏻
