### ISSUE TITLE
tfe_workspace import breaks when using terraform token in variable and remote execution

### ISSUE THREAD

**Issue by kuwas** [terraform-providers/terraform-provider-tfe#93]
**Steps to reproduce**
* Manually create a workspace `default` in https://app.terraform.io
* Add a *Terraform Variable* `tfe_token`, which contains a *User Token* as the secret
* Setup local `~/.terraformrc`
* Create a main.tf like below
* Run `terraform init`
* Run `terraform import tfe_workspace.default <org>/new-workspace`
* Will receive an error
  * `Error: Error reading configuration of workspace new-workspace: unauthorized`

**main.tf**

```
terraform {
  backend "remote" {
    organization = "<org>"
    hostname     = "app.terraform.io"
    workspaces { name = "default" }
  }
}

variable "tfe_token" {}

provider "tfe" {
  token    = var.tfe_token
  hostname = "app.terraform.io"
}

resource "tfe_workspace" "default" {
  organization      = "<org>"
  name              = "new-workspace"
}
```

**Notes**
* I tried setting an environment variable `TFE_TOKEN` in workspace, does not work
* I hardcoded the provider with the token instead of using the variable, works fine
* I tried the token directly using curl to hit the TFE API, works fine
* This seems to be broken for other providers such as AWS as well

Is this behavior because of Terraform Cloud's sensitive "write only" secrets being unreadable when running import from my local machine? If thats the case, then there needs to be an option to run arbitrary commands like import on the remote executor.

**Comment by svanharmelen** [comment]
Hi @kuwas, could you try this again but then with the workspaces block defined as:

```
    workspaces { name = "new-workspace" }
```

The name you reference here, should be the name of the workspace as it exists in Terraform Cloud.

**Comment by kuwas** [comment]
Hi @svanharmelen, the `default` workspace referenced in the backend block is the source workspace running the terraform CD pipeline which is then going to provision the second `new-workspace`. I've actually created the second workspace manually and am attempting the import there.

The whole import workflow is working if I hardcode the token in the provider block and leave everything else as is, this is how I've been working around the issue for now.

**Comment by svanharmelen** [comment]
Ah, I see... I think I didn't read your initial comment correctly the first time, but now reading it again I see what you are trying to do.

The "problem" here is that only [operations are executed remotely](https://www.terraform.io/docs/backends/operations.html), were as commands are always executed locally. Operations in this sense are `refresh`, `plan` and `apply`.

The `remote` backend currently supports the `plan` and `apply` operations, so only they are executed remotely. When trying to run a `refresh` operation, you will get an error saying that the operation is not yet supported.

All other commands (like `import`, `show` or `taint` for example), are executed locally by downloading the state file, executing the command and then uploading the (changed) state file again.

And while it is possible for the `remote` backend to also pull down any variables configured on the workspace, it indeed does not have access to any sensitive values. Currently it will only fetch workspace variables for the `console` command, but any sensitive values are replace with `<sensitive>` instead of the real value.

So at this point in time the only way to solve your issue, is to make sure you make the required token available locally from where you are trying to execute the `import` command. Either by exporting the token or by configuring a credentials block in your [CLI Config FIle](https://www.terraform.io/docs/commands/cli-config.html#credentials) (which is the preferred way to configure TFC credentials).

**Comment by kuwas** [comment]
> Ah, I see... I think I didn't read your initial comment correctly the first time, but now reading it again I see what you are trying to do.
> 
> The "problem" here is that only [operations are executed remotely](https://www.terraform.io/docs/backends/operations.html), were as commands are always executed locally. Operations in this sense are `refresh`, `plan` and `apply`.
> 
> The `remote` backend currently supports the `plan` and `apply` operations, so only they are executed remotely. When trying to run a `refresh` operation, you will get an error saying that the operation is not yet supported.
> 
> All other commands (like `import`, `show` or `taint` for example), are executed locally by downloading the state file, executing the command and then uploading the (changed) state file again.
> 
> And while it is possible for the `remote` backend to also pull down any variables configured on the workspace, it indeed does not have access to any sensitive values. Currently it will only fetch workspace variables for the `console` command, but any sensitive values are replace with `<sensitive>` instead of the real value.
> 
> So at this point in time the only way to solve your issue, is to make sure you make the required token available locally from where you are trying to execute the `import` command. Either by exporting the token or by configuring a credentials block in your [CLI Config FIle](https://www.terraform.io/docs/commands/cli-config.html#credentials) (which is the preferred way to configure TFC credentials).

So I tried setting these credentials a few ways locally, but all of them gave me the same unauthorized response from the API as well.

* Creating a `tfvars` file with the sensitive variable and passing it in using `terraform import -var-file (name).tfvars`
* Setting the credentials block in the `~/.terraformrc` cli config file
* Exporting `TFE_TOKEN` with the credential locally in the shell

If I had to guess, the "<sensitive>" value is being pulled by the `import` command and somehow taking precedence over all the other secrets I provided.

**Comment by svanharmelen** [comment]
Both the second and third option should work. You use a personal token right? And you have rights on the workspaces in question?

So what does a `terraform plan` give you? And can you post the output of your console actions that failed?

**Comment by kuwas** [comment]
@svanharmelen 
* I'm using a personal token
* `~/.terraformrc` uses the personal token
* I am an `owner` on the org
* Workspace `new-workspace` being imported exists and was created manually
* `terraform init` with a remote backend block works
* `terraform plan` with remote execution works

I just tried this again on an empty org, heres the commands and outputs

```
+ terraform init

+ terraform import tfe_workspace.default zoo/new-workspace
Acquiring state lock. This may take a few moments...
tfe_workspace.default: Importing from ID "zoo/new-workspace"...
tfe_workspace.default: Import prepared!
  Prepared tfe_workspace for import
tfe_workspace.default: Refreshing state... [id=zoo/new-workspace]

Error: Error reading configuration of workspace new-workspace: unauthorized

+ terraform import -var-file default.tfvars tfe_workspace.default zoo/new-workspace
Acquiring state lock. This may take a few moments...
tfe_workspace.default: Importing from ID "zoo/new-workspace"...
tfe_workspace.default: Import prepared!
  Prepared tfe_workspace for import
tfe_workspace.default: Refreshing state... [id=zoo/new-workspace]

Error: Error reading configuration of workspace new-workspace: unauthorized


Releasing state lock. This may take a few moments...
```

I converted the sensitive secret to a non-sensitive one, this made import work locally as expected.

**Comment by svanharmelen** [comment]
Interesting! Thank you so much for sending all this info @kuwas. I'm going to have a closer look at the related code and test some things myself as well. Will update here in the next day or so...

**Comment by MartinNowak** [comment]
Any update on this? Also ran into the exact same problem with tf v0.12.23.

**Comment by svanharmelen** [comment]
@kuwas I know it's been a while, sorry for that... I was just looking at this one and don't really understand this comment:

> I converted the remote sensitive secret to a non-sensitive one, this made import work locally as expected.

So did the manually created workspace you are trying to import had a `TFE_TOKEN` sensitive variable configured on the workspace in TFC when it failed? And when you changed that one to being a plain text variable it worked as expected?

**Comment by svanharmelen** [comment]
@MartinNowak does my previous comment apply to your case as well? Or do you have a different setup/issue?

**Comment by MartinNowak** [comment]
I had the same setup. What he meant was that the master workspace ("default") has a sensitive tfe_token which gets used to access Terraform Cloud. It's impossible to import sth. because sensitive variables are neither accessible nor overridable for local commands.

The mentioned workaround was simply to mark the token as non-sensitive so it becomes accessible.

The bug here (apparently also for the AWS Provider) is really the lack of overriding or locally providing such variables.

**Comment by svanharmelen** [comment]
OK, so I just tested this myself but cannot reproduce it using the latest version of the TFE provider (and didn't try with older versions).

My setup looks like this:

1. I have a personal token configured in me `~/.terraformrc` file
2. Manually created a brand new workspace called `sander-test` and configured one sensitive environment variable called `TFE_TOKEN` with my personal token on the workspace.
3. Manually created a second brand new workspace called `sander-new-test`. Didn't configure anything on this workspace, just created it so it can be imported.
4. Created a new `main.tf` containing:
```
terraform {
  backend "remote" {
    organization = "my-test-org"
    workspaces { name = "sander-test" }
  }
}

provider "tfe" {}

resource "tfe_workspace" "default" {
  organization = "my-test-org"
  name         = "sander-new-test"
}
```
5. Run `terraform init`:
```
➜ terraform init                                                                                                                                                                            

Initializing the backend...

Successfully configured the backend "remote"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "tfe" (hashicorp/tfe) 0.17.0...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.tfe: version = "~> 0.17"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```
6. Run `terraform plan`:
```
➜ terraform plan                                                                                                                  
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/my-test-org/sander-test/runs/run-pNL857gSiHvYtrxu

Waiting for the plan to start...

Terraform v0.12.25
Configuring remote state backend...
Initializing Terraform configuration...
2020/05/24 11:53:05 [DEBUG] Using modified User-Agent: Terraform/0.12.25 TFC/c6d59bd658
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # tfe_workspace.default will be created
  + resource "tfe_workspace" "default" {
      + auto_apply            = false
      + external_id           = (known after apply)
      + file_triggers_enabled = true
      + id                    = (known after apply)
      + name                  = "sander-new-test"
      + operations            = true
      + organization          = "my-test-org"
      + queue_all_runs        = true
      + terraform_version     = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```
7. Run `terraform import tfe_workspace.default ws-unxkRhe7dZp9aQXa
```
➜ terraform import tfe_workspace.default ws-unxkRhe7dZp9aQXa                                                                                                                                             
tfe_workspace.default: Importing from ID "ws-unxkRhe7dZp9aQXa"...
tfe_workspace.default: Import prepared!
  Prepared tfe_workspace for import
tfe_workspace.default: Refreshing state... [id=ws-unxkRhe7dZp9aQXa]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
8 Run `terraform plan` again to confirm:
```
➜ terraform plan
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/my-test-org/sander-test/runs/run-sNkVEeB6PsZN7BSj

Waiting for the plan to start...

Terraform v0.12.25
Configuring remote state backend...
Initializing Terraform configuration...
2020/05/24 11:57:14 [DEBUG] Using modified User-Agent: Terraform/0.12.25 TFC/c6d59bd658
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

tfe_workspace.default: Refreshing state... [id=ws-unxkRhe7dZp9aQXa]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # tfe_workspace.default will be updated in-place
  ~ resource "tfe_workspace" "default" {
        auto_apply            = true
        external_id           = "ws-unxkRhe7dZp9aQXa"
      ~ file_triggers_enabled = false -> true
        id                    = "ws-unxkRhe7dZp9aQXa"
        name                  = "sander-new-test"
        operations            = true
        organization          = "my-test-org"
      ~ queue_all_runs        = false -> true
        terraform_version     = "0.12.25"
        trigger_prefixes      = []
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

So what did I miss, what are you doing differently?

Just for the record I also tried it with the exact same files @kuwas posted here, but I needed to call the file `default.auto.tfvars` for it to be picked up. If you didn't need to do that, then did you maybe specify the variable as a `Terraform` var instead of an `Environment` var on the workspace?

With a `default.auto.tfvars` file and the `vars.tfe_token` assigned in the TFE provider block (and still a sensitive `TFE_TOKEN` env var on the `sander-test` workspace), I got the exact same results without any errors.

I guess the first thing we need to do is that one of you tests it again using the latest version of the TFE provider. If the problem persists with the latest version then please try to spot the difference between your test and mine and tell me how I should replicate the problem.

Thanks!

**Comment by kuwas** [comment]
@svanharmelen Since you didn't specify the token to the provider tfe and your import worked, you probably have the environment variable TFE_TOKEN set locally and it was picked up by the provider automatically.

Please try the following example but make sure to:
* Local `TFE_TOKEN` env var is unset
* Variable `tfe_token` is not set locally though `TF_VAR_` env var
* Variable `tfe_token` is set as a terraform variable remotely in the TFE/TFC workspace
* Variable `tfe_token` is referenced by TFE provider as the token argument
* No *.auto.tfvars exist locally or in the repo

```
terraform {
  backend "remote" {
    organization = "<org>"
    hostname     = "app.terraform.io"
    workspaces { name = "default" }
  }
}

variable "tfe_token" {}

provider "tfe" {
  token    = var.tfe_token
  hostname = "app.terraform.io"
}

resource "tfe_workspace" "default" {
  organization      = "<org>"
  name              = "new-workspace"
}
```

- - -

By the way, this issue isnt specific to this provider, I've had to manually provide secrets to the Github, AzureRM, Google providers as well.

I think its caused by the fact that TFE/TFC workspace variable which are write-only are not usable by the terraform import command, which are run locally. If we had the functionality to run import commands from the TFE/TFC UI, then that would resolve this.

Thanks

**Comment by svanharmelen** [comment]
@kuwas see point 1 from my list above:

> 1. I have a personal token configured in my ~/.terraformrc file

So I assume that made it work in my test case.

But I think I'm finally starting to understand what you are trying to do, and probably this provider isn't the best one to explain your issue with as this provider actually supports the same logic to find a valid token as the remote backend does. So in my case, as soon as the remote backend works the import will work as well. 

This will be different when trying to use the AWS provider of course, as that one will require totally different variables. If, in case of the AWS provider, I have my `AWS_TOKEN` configured as a sensitive environment variable on my workspace and then try to import a AWS resource from my laptop, this will indeed fail for the reasons you already expected.

The API calls to interact with the variables on a workspace do not allow you to fetch the values of sensitive variables. This makes sense as otherwise it would become much more difficult (if even possible) to allow someone to use those variables in a controlled and audited workspace, without having to worry about them getting access to the sensitive values and use them outside of TFC (so outside of your audit trail).

So in these cases the import will only succeed if you somehow provide the required values locally in a way that the provider (and your config) supports. In my case for the TFE provider that was easy as without setting a token in the config it will search for a token in your `~/.terraformrc` file which is also needed for the remote backend.

In case of the AWS provider I would maybe have to export the correct values to my environment, or, if in your config you used vars to configure the provider, a `*.auto.tfvars` file with the required values (I think that should work even within that file actually being in you repository, but it does require the person to do the import to have access to the actual values).

But... I guess it's fair to say that this isn't an issue related to this provider, but is in fact an issue with using the `import` command with the `remote backend` in combination with `TFC`. As this is not something that we can fix by making changes to this provider. Instead it would required changes to the remote backend logic in Terraform and/or the APIs in TFC.

So unless I'm still missing something, I will close this issue as it isn't a bug in the TFE provider and cannot be fixed here. The best suggestion I can give you, is to open a support case for your TFC organization and explain the issue there. Support can then log this issue and pass it on to the PO to see which teams should be involved and what (in the greater scheme of things) the priority should be to fix this.

Does that sound fair?

**Comment by kuwas** [comment]
@svanharmelen Yes, I can open an issue using our TFE support portal. Thanks
